### ISSUE TITLE
Fix Django Python files to pass flake8 tests

### ISSUE THREAD

**Issue by AmirMiller91** [beyond-io/picATrip#24]
When testing PR #18, the flake8 tests failed with the following message:

![flake8](https://user-images.githubusercontent.com/67426559/110844888-a214e500-82b2-11eb-93d1-d6be49d0aa80.PNG)

This issue is for fixing the files so they pass the flake8 tests.

**Comment by AmirMiller91** [comment]
I would like to discuss how to fix the F401 issue:
Should the unused imports be removed or commented out (they will probably be needed in the future)?

**Comment by maayanhd** [comment]
I believe for now it should just be commented out since we don't really know how they would be used in the future potentially as you said
