### ISSUE TITLE
Better name to apphomepage

### ISSUE THREAD

**Issue by nadavspinco** [beyond-io/picATrip#35]
The folder that contains the views/models files named apphomepage.
I chose that name when I created the home page and now he seems wrong. 
Please suggest a better name for this folder.

**Comment by Leeadar** [comment]
How about 'PicATrip_web' ?

**Comment by EdDev** [comment]
> How about 'PicATrip_web' ?

I personally do not like camel-case files or folders in a project.
But I have no strong feelings about it.

**Comment by Leeadar** [comment]
So maybe just 'Web'? Or 'Main'?

**Comment by EdDev** [comment]
> So maybe just 'Web'? Or 'Main'?

it has camel case as well :)
I would go and check a famous django based project (or two) and look what was used there.
Maybe there are even examples that hint how it should be named in formal documents.

**Comment by Leeadar** [comment]
So we can use the name 'main' for now, and if we will want to add more templates we will consider to change the name?
I didn't find a common name that being used.

**Comment by nadavspinco** [comment]
@Leeadar and I looked at some Django projects and we didn't found a clear best practice, but we both agreed that pickATrip_django_apps is a better name for this dir.
The path : pickATrip/pickATrip_django_apps/homepage is more clear
