### ISSUE TITLE
Adding urls tests

### ISSUE THREAD

**Issue by nadavspinco** [beyond-io/picATrip#89]
for each URL on our site, we need to check that it is referring to the correct view.

**Comment by maayanhd** [comment]
also you should check the objects that has been sent to the view are equal to the expected objects for example check in the comments page if there's 5 comments at most, for the specific post it refers to

**Comment by nadavspinco** [comment]
I don't understand what do you mean. I want to check if the URL is mapping to the right view, nothing more than that.

**Comment by maayanhd** [comment]
did you forget to close it by linking it to the PR? It should be closed or are you planning make another PR referring to this issue @nadavspinco ?

**Comment by nadavspinco** [comment]
> did you forget to close it by linking it to the PR? It should be closed or are you planning make another PR referring to this issue @nadavspinco ?

No, I forgot to link the pr to this issue.
