### ISSUE TITLE
signing in is not working

### ISSUE THREAD

**Issue by maayanhd** [beyond-io/picATrip#98]
0. vagrant up --provision 
1. go to localhost:8000/register
2. fill in details and continue
3. it throws an exception : 
![image](https://user-images.githubusercontent.com/48455448/116250158-22fe4200-a776-11eb-9939-cb5a5d36855f.png)

**Comment by Leeadar** [comment]
It is working for me. did you rebase?

**Comment by maayanhd** [comment]
No, it's happening on the main branch, @Shoval-Ovadia had an issue perhaps similar lately, specifically accessing the commenting page that requires behind the scene registration (it won't allow you to enter if your not registered), so it might be another indication but maybe not

**Comment by maayanhd** [comment]
solved after these following steps:
1. running vagrant halt, 
2. erasing the db.sqlite3 file
3. running vagrant up --provision
